name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    services:
      postgres:
        image: postgres:latest-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DB_URL: "postgres://postgres:password@localhost:5432"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby & gems  
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
        with:
          bundler-cache: true
      - name: Setup DB
        run: bin/rails db:prepare

