name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DB_URL: "postgres://postgres:password@localhost:5432"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing RVM
        run: \curl -sSL https://get.rvm.io | bash -s stable --ruby
      - name: Installing Ruby v3.3.0
        run: rvm fetch ruby-3.3.0 && rvm install ruby-3.3.0
      - name: Bundle install
        run: gem install bundler && bundle install
      - name: Setup DB
        run: bin/rails db:prepare

