name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DB_URL: "postgres://postgres:password@localhost:5432"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ruby 
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Dependencies
        run: bundle install
      - name: Setup DB
        run: bin/rails db:prepare
  mobile:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./mobile
    strategy:
      matrix:
        os: [ ios, android ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}
      - name: Install JDK v17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Prebuild
        run: yarn expo prebuild
      - name: Build Android
        if: matrix.os == 'android'
        run: eas build --platform android --profile production --non-interactive --local
      - name: Build iOS
        if: matrix.os == 'ios'
        run: eas build --platform ios --profile production --non-interactive --local