name: "Dev CI"
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            lib: ${{ steps.changes.outputs.lib }}
        steps:
            - uses: actions/checkout@v5
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                  filters: |
                      lib:
                        - 'lib/**'
    shared_lib:
        runs-on: ubuntu-latest
        needs: changes
        if: ${{ steps.changes.outputs.lib == 'true' }}
            defaults:
              run:
                working-directory: ./web
        steps:
            - uses: actions/checkout@v5
            - name: Install build cli
              run: cargo install nj-cli
            - name: Build
              run: nj-cli build
        

